# Generated by Django 4.2.2 on 2023-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('type', models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('select', 'Select'), ('integer', 'Integer'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(max_length=45, null=True)),
                ('hint', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('data_attrs', models.JSONField(blank=True, null=True)),
                ('items', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'additional_questions',
            },
        ),
        migrations.CreateModel(
            name='JobSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('type', models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('select', 'Select'), ('integer', 'Integer'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(max_length=45, null=True)),
                ('hint', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('data_attrs', models.JSONField(blank=True, null=True)),
                ('items', models.JSONField(null=True)),
                ('platform', models.CharField(default='linkedin', max_length=20)),
            ],
            options={
                'db_table': 'job_search_filters',
            },
        ),
    ]
