# Generated by Django 4.2.2 on 2023-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_additionalquestion_slug_jobsearchfilter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalquestion',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='can_be_added_in_search_url',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='element_xpath',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='fillable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='filter_name',
            field=models.CharField(default='test', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='query_param',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='jobsearchfilter',
            name='should_be_triggered_in_search_platform',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='additionalquestion',
            name='type',
            field=models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('number_input', 'Number Input'), ('select', 'Select'), ('integer', 'Integer'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select'), ('switch_button', 'Switch Button')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobsearchfilter',
            name='type',
            field=models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('number_input', 'Number Input'), ('select', 'Select'), ('integer', 'Integer'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select'), ('switch_button', 'Switch Button')], max_length=25),
        ),
    ]
