# Generated by Django 4.2.2 on 2023-08-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_additionalquestion_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalquestion',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='jobsearchfilter',
            options={'ordering': ('order',)},
        ),
    ]
