# Generated by Django 4.2.2 on 2023-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_additionalquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalquestion',
            name='type',
            field=models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('number_input', 'Number Input'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select'), ('switch_button', 'Switch Button')], max_length=25),
        ),
        migrations.AlterField(
            model_name='jobsearchfilter',
            name='type',
            field=models.CharField(choices=[('multi_input', 'Multi Input'), ('input', 'Input'), ('number_input', 'Number Input'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox_group', 'Checkbox Group'), ('multi_select', 'Multi Select'), ('switch_button', 'Switch Button')], max_length=25),
        ),
    ]
