# Generated by Django 4.2.2 on 2023-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_additionalquestion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchfilter',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
