# Generated by Django 4.2.2 on 2023-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_signup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_welcome_said',
            field=models.BooleanField(default=False),
        ),
    ]
