# Generated by Django 4.2.2 on 2023-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
