# Generated by Django 4.2.2 on 2024-03-08 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userskill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResumeParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('data', models.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_resume_parsed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_resume_parsed',
            },
        ),
    ]
