# Generated by Django 4.2.2 on 2023-08-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('title', models.CharField(max_length=125)),
                ('job_url', models.URLField()),
                ('job_id', models.CharField(max_length=40)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn')], default='linkedin', max_length=25)),
                ('status', models.CharField(choices=[('created', 'Created'), ('applied', 'Applied'), ('failed', 'Failed')], default='created', max_length=25)),
                ('company', models.CharField(max_length=125, null=True)),
            ],
            options={
                'db_table': 'applied_jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppliedJobQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('answer_options', models.JSONField(blank=True, null=True)),
                ('prefilled_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_applying.appliedjob')),
            ],
            options={
                'db_table': 'applied_job_question_answers',
            },
        ),
    ]
