# Generated by Django 4.2.2 on 2023-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applying', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='powered_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
