# Generated by Django 4.2.2 on 2023-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applying', '0004_appliedjob_powered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='job_url',
            field=models.URLField(max_length=800),
        ),
    ]
