# Generated by Django 4.2.2 on 2023-10-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applying', '0005_alter_appliedjob_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('applied', 'Applied'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=25),
        ),
    ]
