# Generated by Django 4.2.2 on 2024-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applying', '0006_alter_appliedjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobqa',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobqa',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
