# Generated by Django 4.2.2 on 2023-08-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('advanced', 'Advanced')], max_length=25, unique=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, max_length=8)),
                ('currency', models.CharField(choices=[('usd', 'USD')], default='usd', max_length=10)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/plan_images/')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='PlanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('resumes_count', 'Resume'), ('job_title', 'Job title'), ('job_applications', 'Job applications'), ('free_access', 'Free Access'), ('submission_tracker', 'Job submission tracker'), ('filter_companies', 'Filter out companies'), ('job_applies_per_day', 'Job applies per day')], max_length=30)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plan_options',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.plan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
