# Generated by Django 4.2.2 on 2023-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
