# Generated by Django 4.2.2 on 2023-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_plan_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_webhook_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_webhook_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
