# Generated by Django 4.2.2 on 2023-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_subscription_stripe_webhook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
